name = "nytotoxnk"
compatibility_date = "2024-03-31"
main = ".vercel/output/functions/_worker.js"
pages_build_output_dir = ".vercel/output"

[site]
bucket = ".vercel/output/static"

[build]
command = "npm run build && npx @cloudflare/next-on-pages"

[[kv_namespaces]]
binding = "BLOG_DATA"
id = "607059d6b5374ae7b2927373ad7d4509"
preview_id = "5b1da8a51f794f76b08d843021acb244"

[vars]
ENVIRONMENT = "production"
API_SECRET = "100e11ea0f87724622e73e2d3ec69bb145dcb89cf81e9c46e0f1ff71fda18a55"

[env.development]
name = "blog-api-dev"
[env.development.vars]
ENVIRONMENT = "development" 

[observability.logs]
enabled = true