# Basic configuration for Cloudflare Pages
name = "nytotoxnk"
compatibility_date = "2024-03-31"

# KV namespace for blog data (if needed)
[[kv_namespaces]]
binding = "BLOG_DATA"
id = "607059d6b5374ae7b2927373ad7d4509"
preview_id = "5b1da8a51f794f76b08d843021acb244"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_SECRET = "100e11ea0f87724622e73e2d3ec69bb145dcb89cf81e9c46e0f1ff71fda18a55"

[env.preview.vars]
ENVIRONMENT = "preview" 